//! AI-powered Tauri commands.
//!
//! # Locking discipline
//!
//! Every async command must:
//! 1. Lock state to clone/extract what it needs.
//! 2. **Drop the lock guard** before the first `.await`.
//! 3. Re-lock if SQLite mutations are needed after the LLM call.
//!
//! This ensures `parking_lot::Mutex` guards are never held across await points,
//! which would deadlock the Tauri async runtime.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use tauri::State;
use uuid::Uuid;

use csview_engine::chart::{self, ChartData, ChartError, ChartSpec};
use csview_engine::engine::{ColumnKind, ColumnMeta};
use csview_engine::quality::{self, IssueType, QualityIssue};
use csview_engine::sqlite_store::SchemaContext;
use csview_engine::stats_extended::{self, AnomalyResult, ExtendedColumnStats};

use crate::commands_csv::CommandError;
use crate::llm::client::{
    available_models, LlmClient, Provider, ToolDefinition, ToolEvent, ToolReply,
};
use crate::llm::types::LlmError;
use crate::llm::prompts;
use crate::state::AiAppState;

// ---------------------------------------------------------------------------
// Result types
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AccountStatus {
    pub has_api_key: bool,
    pub provider: String,
    pub model: String,
    pub available_models: Vec<AvailableModel>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AvailableModel {
    pub id: String,
    pub name: String,
    pub provider: String,
    pub tier: String,
    pub description: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NlQueryResult {
    /// The WHERE clause generated by the LLM.
    pub where_clause: String,
    /// Full SELECT statement executed.
    pub sql: String,
    pub columns: Vec<String>,
    pub rows: Vec<Vec<serde_json::Value>>,
    pub row_count: usize,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProfileReport {
    /// The markdown narrative written by the LLM.
    pub markdown: String,
    /// Raw column stats as JSON for the frontend to use if desired.
    pub stats: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TransformResult {
    /// The SQL expression generated by the LLM.
    pub expression: String,
    /// The column name suggested by the LLM.
    pub column_name: String,
    /// Number of rows updated (matches row_count of the store).
    pub rows_updated: usize,
}

/// Intermediate type for LLM transform JSON response.
#[derive(Debug, Deserialize)]
struct TransformLlmResponse {
    expression: String,
    column_name: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AnomalyReport {
    /// LLM-written narrative.
    pub markdown: String,
    /// Raw anomaly results.
    pub anomalies: Vec<AnomalyResult>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupByReport {
    /// The GROUP BY query generated by the LLM.
    pub sql: String,
    pub title: String,
    pub description: String,
    pub columns: Vec<String>,
    pub rows: Vec<Vec<serde_json::Value>>,
    pub row_count: usize,
}

/// Intermediate type for LLM group-by JSON response.
#[derive(Debug, Deserialize)]
struct GroupByLlmResponse {
    sql: String,
    title: String,
    description: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QualityReport {
    pub markdown: String,
    pub issues: Vec<QualityIssueSer>,
    pub issue_count: usize,
}

/// Serialisable quality issue (mirrors `QualityIssue` but fully owned).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QualityIssueSer {
    pub row: usize,
    pub column: usize,
    pub issue_type: String,
    pub value: String,
    pub suggestion: Option<String>,
    pub is_pii: bool,
}

impl From<&QualityIssue> for QualityIssueSer {
    fn from(q: &QualityIssue) -> Self {
        let is_pii = matches!(q.issue_type, IssueType::PossiblePii(_));
        let issue_type = format!("{:?}", q.issue_type);
        Self {
            row: q.row,
            column: q.column,
            issue_type,
            value: q.value.clone(),
            suggestion: q.suggestion.clone(),
            is_pii,
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatSession {
    pub session_id: String,
    pub file_id: String,
    pub created_at: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatResponse {
    pub session_id: String,
    pub message: String,
    pub role: String,
    /// Optional chart payload — populated when the model called the
    /// `make_chart` tool during this turn. Multiple charts in one reply
    /// would each appear once `make_chart` is called more than once.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub charts: Vec<ChartData>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Report {
    pub report_id: String,
    pub title: String,
    pub markdown: String,
}

/// Intermediate type for LLM report JSON response.
#[derive(Debug, Deserialize)]
struct ReportLlmResponse {
    title: String,
    markdown: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JoinSuggestion {
    pub left_key: String,
    pub right_key: String,
    pub join_type: String,
    pub rationale: String,
}

/// Intermediate type for LLM join-suggestion JSON response.
#[derive(Debug, Deserialize)]
struct JoinLlmResponse {
    left_key: String,
    right_key: String,
    join_type: String,
    rationale: String,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PiiColumn {
    pub column_name: String,
    pub pii_kind: String,
    pub sample_values: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ComplianceReport {
    pub markdown: String,
    pub pii_columns: Vec<PiiColumn>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ForecastReport {
    pub markdown: String,
    pub slope: f64,
    pub intercept: f64,
    pub r_squared: f64,
    pub n: usize,
    pub x_col: String,
    pub y_col: String,
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn llm_error_to_command_error(e: LlmError) -> CommandError {
    CommandError::Sqlite(format!("llm error: {e}"))
}

/// Clone the `LlmClient` out of state (or return an error if not set).
fn get_llm(state: &AiAppState) -> Result<LlmClient, CommandError> {
    state
        .llm
        .lock()
        .clone()
        .ok_or_else(|| CommandError::InvalidArg("no API key set — call set_api_key first".into()))
}

/// Extract schema context for a file while holding the lock, then release.
fn get_schema(state: &AiAppState, file_id: &str) -> Result<SchemaContext, CommandError> {
    let stores = state.stores.lock();
    let store = stores
        .get(file_id)
        .ok_or_else(|| CommandError::UnknownFile(file_id.to_string()))?;
    store.schema_context(5).map_err(CommandError::from)
}

/// Read all rows from the store as `Vec<Vec<String>>` (for engine functions).
fn read_all_rows(state: &AiAppState, file_id: &str) -> Result<(Vec<ColumnMeta>, Vec<Vec<String>>), CommandError> {
    let stores = state.stores.lock();
    let store = stores
        .get(file_id)
        .ok_or_else(|| CommandError::UnknownFile(file_id.to_string()))?;

    let cols: Vec<ColumnMeta> = store.columns().to_vec();
    let result = store.query("SELECT * FROM data").map_err(CommandError::from)?;
    let rows: Vec<Vec<String>> = result
        .rows
        .into_iter()
        .map(|row| {
            row.into_iter()
                .map(|v| match v {
                    serde_json::Value::String(s) => s,
                    serde_json::Value::Null => String::new(),
                    other => other.to_string(),
                })
                .collect()
        })
        .collect();
    Ok((cols, rows))
}

// ---------------------------------------------------------------------------
// Account commands
// ---------------------------------------------------------------------------

/// Store an API key + provider + model and initialise the LLM client.
#[tauri::command]
pub async fn set_api_key(
    state: State<'_, AiAppState>,
    provider: String,
    key: String,
    model: String,
) -> Result<(), CommandError> {
    if key.trim().is_empty() {
        return Err(CommandError::InvalidArg("API key must not be empty".into()));
    }
    if model.trim().is_empty() {
        return Err(CommandError::InvalidArg(
            "Model must not be empty — pick one from the model list before saving".into(),
        ));
    }
    let prov = match provider.to_lowercase().as_str() {
        "openai" => Provider::OpenAI,
        "google" => Provider::Google,
        "anthropic" => Provider::Anthropic,
        _ => return Err(CommandError::InvalidArg(format!("unknown provider: {provider}"))),
    };
    // We deliberately do NOT validate `model` against a static allowlist —
    // providers ship new model ids regularly and we surface them via the
    // refresh button (see `fetch_provider_models`). The non-empty check
    // above is enough to prevent the "you must provide a model" 400.
    let client = LlmClient::new(prov, key.clone(), model.clone());

    {
        let db = state.app_db.lock();
        db.execute(
            "INSERT OR REPLACE INTO account (id, api_key, model) VALUES (1, ?1, ?2)",
            rusqlite::params![format!("{provider}:{key}"), model],
        )
        .map_err(|e| CommandError::Sqlite(e.to_string()))?;
    }

    *state.llm.lock() = Some(client);
    Ok(())
}

/// Check whether an API key is currently configured and return available models.
#[tauri::command]
pub fn get_account_status(state: State<'_, AiAppState>) -> Result<AccountStatus, CommandError> {
    let guard = state.llm.lock();
    let (has_api_key, provider, model) = match guard.as_ref() {
        Some(client) => (true, format!("{}", client.provider()), client.model().to_string()),
        None => (false, String::new(), String::new()),
    };
    drop(guard);
    Ok(AccountStatus {
        has_api_key,
        provider,
        model,
        available_models: available_models()
            .into_iter()
            .map(|m| AvailableModel {
                id: m.id,
                name: m.name,
                provider: format!("{}", m.provider),
                tier: format!("{:?}", m.tier).to_lowercase(),
                description: m.description,
            })
            .collect(),
    })
}

/// Fetch the live model catalogue from a provider, using a freshly-supplied
/// API key (so the user can probe before committing). Returns the same
/// `AvailableModel` shape the AccountPanel already renders.
#[tauri::command]
pub async fn fetch_provider_models(
    provider: String,
    key: String,
) -> Result<Vec<AvailableModel>, CommandError> {
    if key.trim().is_empty() {
        return Err(CommandError::InvalidArg(
            "API key required to list models".into(),
        ));
    }
    let prov = match provider.to_lowercase().as_str() {
        "openai" => Provider::OpenAI,
        "google" => Provider::Google,
        "anthropic" => Provider::Anthropic,
        _ => return Err(CommandError::InvalidArg(format!("unknown provider: {provider}"))),
    };
    // Model arg is unused for the listing endpoint; pass a placeholder.
    let client = LlmClient::new(prov, key, String::new());
    let models = client.fetch_models().await.map_err(llm_error_to_command_error)?;
    Ok(models
        .into_iter()
        .map(|m| AvailableModel {
            id: m.id,
            name: m.name,
            provider: format!("{}", m.provider),
            tier: format!("{:?}", m.tier).to_lowercase(),
            description: m.description,
        })
        .collect())
}

/// Default model for each provider when only an env-var key is found and no
/// previous selection has been persisted.
fn default_model_for(provider: Provider) -> &'static str {
    match provider {
        Provider::Anthropic => "claude-sonnet-4-20250514",
        Provider::OpenAI => "gpt-4.1",
        Provider::Google => "gemini-2.5-flash",
    }
}

/// Restore a previously saved (provider, key, model) row from the app DB.
/// Returns the configured client, or None if nothing is saved.
fn load_saved_account(state: &AiAppState) -> Option<LlmClient> {
    let db = state.app_db.lock();
    let row: Option<(String, String)> = db
        .query_row(
            "SELECT api_key, model FROM account WHERE id = 1",
            [],
            |r| Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?)),
        )
        .ok();
    drop(db);
    let (combined, model) = row?;
    // The api_key column stores "{provider}:{actual_key}" (see set_api_key).
    let (provider_str, key) = combined.split_once(':')?;
    let provider = match provider_str.to_lowercase().as_str() {
        "openai" => Provider::OpenAI,
        "google" => Provider::Google,
        "anthropic" => Provider::Anthropic,
        _ => return None,
    };
    if key.is_empty() || model.is_empty() {
        return None;
    }
    Some(LlmClient::new(provider, key.to_string(), model))
}

/// Configure the LLM client on startup. Priority:
///   1. Previously saved account in the local DB (whatever the user last picked).
///   2. ANTHROPIC_API_KEY env var → default Anthropic model.
///   3. OPENAI_API_KEY env var → default OpenAI model.
///   4. GEMINI_API_KEY env var → default Google model.
///
/// The first match wins so a user-configured choice is never silently
/// overwritten by an env var hanging around in the shell.
pub fn auto_detect_keys(state: &AiAppState) {
    if let Some(client) = load_saved_account(state) {
        *state.llm.lock() = Some(client);
        return;
    }
    let candidates = [
        ("ANTHROPIC_API_KEY", Provider::Anthropic),
        ("OPENAI_API_KEY", Provider::OpenAI),
        ("GEMINI_API_KEY", Provider::Google),
    ];
    for (env_var, provider) in candidates {
        if let Ok(key) = std::env::var(env_var) {
            if !key.is_empty() {
                let client = LlmClient::new(
                    provider,
                    key,
                    default_model_for(provider).to_string(),
                );
                *state.llm.lock() = Some(client);
                return;
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Feature 1 — NL query → SQL WHERE
// ---------------------------------------------------------------------------

/// Translate a natural-language query into a SQL WHERE clause and execute it.
#[tauri::command]
pub async fn nl_query(
    state: State<'_, AiAppState>,
    file_id: String,
    query: String,
) -> Result<NlQueryResult, CommandError> {
    // 1. Extract what we need — drop the lock before await.
    let schema = get_schema(&state, &file_id)?;
    let llm = get_llm(&state)?;
    let table = schema.table_name.clone();

    // 2. Call LLM (no locks held).
    let (system, user_msg) = prompts::nl_query_prompt(&schema, &query);
    let where_clause = llm
        .complete(&system, &user_msg, 256)
        .await
        .map_err(llm_error_to_command_error)?;
    let where_clause = where_clause.trim().to_string();

    // 3. Execute SQL — re-lock.
    let sql = format!("SELECT * FROM {table} WHERE {where_clause}");
    let result = {
        let stores = state.stores.lock();
        let store = stores
            .get(&file_id)
            .ok_or_else(|| CommandError::UnknownFile(file_id.clone()))?;
        store.query(&sql).map_err(CommandError::from)?
    };

    // 4. Persist query history.
    {
        let db = state.app_db.lock();
        let _ = db.execute(
            "INSERT INTO query_history (file_path, nl_query, generated_sql) VALUES (?1, ?2, ?3)",
            rusqlite::params![file_id, query, sql.clone()],
        );
    }

    Ok(NlQueryResult {
        where_clause,
        sql,
        columns: result.columns,
        rows: result.rows,
        row_count: result.row_count,
    })
}

// ---------------------------------------------------------------------------
// Feature 2 — Data profile
// ---------------------------------------------------------------------------

/// Compute per-column statistics and ask the LLM to write a narrative report.
#[tauri::command]
pub async fn generate_profile(
    state: State<'_, AiAppState>,
    file_id: String,
) -> Result<ProfileReport, CommandError> {
    let schema = get_schema(&state, &file_id)?;
    let llm = get_llm(&state)?;
    let (columns, rows) = read_all_rows(&state, &file_id)?;

    // Compute extended stats per numeric column.
    let stats_map: HashMap<String, ExtendedColumnStats> = columns
        .iter()
        .filter(|c| matches!(c.kind, ColumnKind::Integer | ColumnKind::Float))
        .map(|c| {
            let col_vals: Vec<&str> = rows
                .iter()
                .map(|r| r.get(c.index).map(String::as_str).unwrap_or(""))
                .collect();
            let stats = stats_extended::extended_stats(&col_vals);
            (c.name.clone(), stats)
        })
        .collect();

    let stats_json = serde_json::to_string_pretty(&stats_map).unwrap_or_default();
    let (system, user_msg) = prompts::data_profile_prompt(&schema, &stats_json);
    let markdown = llm
        .complete(&system, &user_msg, 1024)
        .await
        .map_err(llm_error_to_command_error)?;

    Ok(ProfileReport {
        markdown,
        stats: serde_json::from_str(&stats_json).unwrap_or(serde_json::Value::Null),
    })
}

// ---------------------------------------------------------------------------
// Feature 3 — Column transform
// ---------------------------------------------------------------------------

/// Ask the LLM to generate a SQL expression, then add the derived column.
#[tauri::command]
pub async fn nl_transform(
    state: State<'_, AiAppState>,
    file_id: String,
    query: String,
) -> Result<TransformResult, CommandError> {
    let schema = get_schema(&state, &file_id)?;
    let llm = get_llm(&state)?;

    let (system, user_msg) = prompts::column_transform_prompt(&schema, &query);
    let resp: TransformLlmResponse = llm
        .complete_json(&system, &user_msg, 256)
        .await
        .map_err(llm_error_to_command_error)?;

    let rows_updated = {
        let stores = state.stores.lock();
        let store = stores
            .get(&file_id)
            .ok_or_else(|| CommandError::UnknownFile(file_id.clone()))?;
        store
            .add_column(&resp.column_name, &resp.expression)
            .map_err(CommandError::from)?;
        store.row_count()
    };

    Ok(TransformResult {
        expression: resp.expression,
        column_name: resp.column_name,
        rows_updated,
    })
}

// ---------------------------------------------------------------------------
// Feature 4 — Anomaly detection
// ---------------------------------------------------------------------------

/// Detect statistical outliers in numeric columns, then ask the LLM to narrate.
#[tauri::command]
pub async fn detect_anomalies_cmd(
    state: State<'_, AiAppState>,
    file_id: String,
    columns: Vec<String>,
) -> Result<AnomalyReport, CommandError> {
    let schema = get_schema(&state, &file_id)?;
    let llm = get_llm(&state)?;
    let (col_metas, rows) = read_all_rows(&state, &file_id)?;

    // Determine which column indices to scan.
    let col_indices: Vec<usize> = if columns.is_empty() {
        col_metas
            .iter()
            .filter(|c| matches!(c.kind, ColumnKind::Integer | ColumnKind::Float))
            .map(|c| c.index)
            .collect()
    } else {
        columns
            .iter()
            .filter_map(|name| col_metas.iter().find(|c| &c.name == name))
            .map(|c| c.index)
            .collect()
    };

    let anomalies = csview_engine::detect_anomalies(&rows, &col_metas, &col_indices, 3.0);

    let anomaly_json = serde_json::to_string_pretty(&anomalies).unwrap_or_default();
    let (system, user_msg) = prompts::anomaly_prompt(&schema, &anomaly_json);
    let markdown = llm
        .complete(&system, &user_msg, 768)
        .await
        .map_err(llm_error_to_command_error)?;

    Ok(AnomalyReport { markdown, anomalies })
}

// ---------------------------------------------------------------------------
// Feature 5 — Smart grouping
// ---------------------------------------------------------------------------

/// Translate a natural-language aggregation request into a GROUP BY query.
#[tauri::command]
pub async fn smart_group(
    state: State<'_, AiAppState>,
    file_id: String,
    query: String,
) -> Result<GroupByReport, CommandError> {
    let schema = get_schema(&state, &file_id)?;
    let llm = get_llm(&state)?;

    let (system, user_msg) = prompts::smart_group_prompt(&schema, &query);
    let resp: GroupByLlmResponse = llm
        .complete_json(&system, &user_msg, 512)
        .await
        .map_err(llm_error_to_command_error)?;

    let result = {
        let stores = state.stores.lock();
        let store = stores
            .get(&file_id)
            .ok_or_else(|| CommandError::UnknownFile(file_id.clone()))?;
        store.query(&resp.sql).map_err(CommandError::from)?
    };

    Ok(GroupByReport {
        sql: resp.sql,
        title: resp.title,
        description: resp.description,
        columns: result.columns,
        rows: result.rows,
        row_count: result.row_count,
    })
}

// ---------------------------------------------------------------------------
// Feature 6 — Data quality audit
// ---------------------------------------------------------------------------

/// Run the engine's quality scan and ask the LLM to narrate the findings.
#[tauri::command]
pub async fn audit_quality(
    state: State<'_, AiAppState>,
    file_id: String,
) -> Result<QualityReport, CommandError> {
    let schema = get_schema(&state, &file_id)?;
    let llm = get_llm(&state)?;
    let (col_metas, rows) = read_all_rows(&state, &file_id)?;

    let mut all_issues: Vec<QualityIssue> = Vec::new();
    for meta in &col_metas {
        let col_vals: Vec<&str> = rows
            .iter()
            .map(|r| r.get(meta.index).map(String::as_str).unwrap_or(""))
            .collect();
        let col_issues = quality::audit_column(&col_vals, meta, meta.index);
        all_issues.extend(col_issues);
    }

    let serialisable: Vec<QualityIssueSer> = all_issues.iter().map(QualityIssueSer::from).collect();
    let issues_json = serde_json::to_string_pretty(&serialisable).unwrap_or_default();

    let (system, user_msg) = prompts::quality_audit_prompt(&schema, &issues_json);
    let markdown = llm
        .complete(&system, &user_msg, 1024)
        .await
        .map_err(llm_error_to_command_error)?;

    let issue_count = serialisable.len();
    Ok(QualityReport { markdown, issues: serialisable, issue_count })
}

// ---------------------------------------------------------------------------
// Feature 7 — Chat
// ---------------------------------------------------------------------------

/// Create a new chat session for the given file.
#[tauri::command]
pub fn new_chat_session(
    state: State<'_, AiAppState>,
    file_id: String,
) -> Result<ChatSession, CommandError> {
    let session_id = Uuid::new_v4().to_string();
    let now = chrono::Utc::now().to_rfc3339();

    {
        let db = state.app_db.lock();
        db.execute(
            "INSERT INTO chat_sessions (id, file_path, created_at, updated_at) VALUES (?1, ?2, ?3, ?3)",
            rusqlite::params![session_id, file_id, now],
        )
        .map_err(|e| CommandError::Sqlite(e.to_string()))?;
    }

    Ok(ChatSession { session_id, file_id, created_at: now })
}

/// Send a message to an open chat session and receive the assistant reply.
#[tauri::command]
pub async fn chat_message(
    state: State<'_, AiAppState>,
    file_id: String,
    session_id: String,
    message: String,
) -> Result<ChatResponse, CommandError> {
    let schema = get_schema(&state, &file_id)?;
    let llm = get_llm(&state)?;

    // Load conversation history — collect fully before dropping db lock.
    let history: Vec<(String, String)> = {
        let db = state.app_db.lock();
        let mut stmt = db
            .prepare(
                "SELECT role, content FROM chat_messages \
                 WHERE session_id = ?1 ORDER BY id ASC",
            )
            .map_err(|e| CommandError::Sqlite(e.to_string()))?;
        let pairs: Vec<(String, String)> = stmt
            .query_map(rusqlite::params![session_id], |row| {
                Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
            })
            .map_err(|e| CommandError::Sqlite(e.to_string()))?
            .filter_map(|r| r.ok())
            .collect();
        drop(stmt);
        drop(db);
        pairs
    };

    let mut events: Vec<ToolEvent> = history
        .into_iter()
        .map(|(role, content)| match role.as_str() {
            "assistant" => ToolEvent::AssistantText(content),
            _ => ToolEvent::User(content),
        })
        .collect();
    events.push(ToolEvent::User(message.clone()));

    let tools = vec![chart_tool_definition()];
    let system = prompts::chat_system_prompt(&schema);

    // Tool-use loop. Each round either completes with text (return to user)
    // or emits a tool call we execute locally and feed back. Cap rounds to
    // prevent runaway costs if the model gets stuck.
    //
    // Token budget needs to be generous: reasoning models (gpt-5.x, o-series)
    // burn tokens on hidden reasoning before producing any visible text,
    // and 2048 was tight enough that chats sometimes exhausted budget mid
    // narrative.
    const TOOL_LOOP_TOKENS: u32 = 4096;
    const FINAL_NARRATIVE_TOKENS: u32 = 2048;
    const MAX_ROUNDS: usize = 5;

    let mut charts: Vec<ChartData> = Vec::new();
    let mut final_text = String::new();
    let mut hit_cap = false;
    for round in 0..MAX_ROUNDS {
        let reply = llm
            .chat_with_tools(&system, &events, &tools, TOOL_LOOP_TOKENS)
            .await
            .map_err(llm_error_to_command_error)?;
        match reply {
            ToolReply::Text(text) => {
                final_text = text;
                break;
            }
            ToolReply::ToolCall { call_id, name, arguments } => {
                if name != "make_chart" {
                    final_text = format!("(model requested unknown tool `{name}`)");
                    break;
                }
                let spec: ChartSpec = serde_json::from_value(arguments.clone())
                    .map_err(|e| CommandError::InvalidArg(format!("bad chart spec: {e}")))?;
                eprintln!(
                    "[chat] round {round}: tool call make_chart \
                     kind={:?} x={} y={:?} agg={:?}",
                    spec.chart_type, spec.x_column, spec.y_column, spec.aggregation
                );
                events.push(ToolEvent::AssistantToolCall {
                    call_id: call_id.clone(),
                    name: name.clone(),
                    arguments,
                });
                // Execute the tool locally — no LLM-generated values reach
                // the rendered chart, only the choice of columns and shape.
                let tool_output = match run_make_chart(&state, &file_id, spec) {
                    Ok(data) => {
                        eprintln!(
                            "[chat] round {round}: chart rendered ({} rows)",
                            data.rows.len()
                        );
                        let summary = chart_summary_for_llm(&data);
                        charts.push(data);
                        summary
                    }
                    Err(e) => {
                        eprintln!("[chat] round {round}: chart error: {e}");
                        format!("{{\"error\": {:?}}}", e.to_string())
                    }
                };
                events.push(ToolEvent::ToolResult {
                    call_id,
                    output: tool_output,
                });
                if round + 1 == MAX_ROUNDS {
                    hit_cap = true;
                }
            }
        }
    }

    // If we exited the loop with charts in hand but no narrative text,
    // do one final tools-disabled call to force the model to actually
    // describe what it just rendered. The cap prompt explicitly says
    // "no more tools" so the model can't bounce off into another round.
    if final_text.is_empty() && !charts.is_empty() {
        eprintln!(
            "[chat] forcing narrative-only call after {} chart(s){}",
            charts.len(),
            if hit_cap { " (hit iteration cap)" } else { "" }
        );
        let narrative_events = events.clone();
        match llm
            .chat_with_tools(
                &format!(
                    "{system}\n\n\
                     The chart(s) the user requested have already been \
                     rendered for them via the make_chart tool. Do NOT \
                     call any more tools. Reply with a brief one or two \
                     sentence interpretation of what the chart(s) show.",
                ),
                &narrative_events,
                &[],
                FINAL_NARRATIVE_TOKENS,
            )
            .await
        {
            Ok(ToolReply::Text(t)) => final_text = t,
            Ok(ToolReply::ToolCall { name, .. }) => {
                eprintln!(
                    "[chat] narrative-only call returned a tool call ({name}); ignoring"
                );
                final_text = format!(
                    "Rendered {} chart{}.",
                    charts.len(),
                    if charts.len() == 1 { "" } else { "s" }
                );
            }
            Err(e) => {
                eprintln!("[chat] narrative-only call failed: {e}");
                final_text = format!(
                    "Rendered {} chart{}.",
                    charts.len(),
                    if charts.len() == 1 { "" } else { "s" }
                );
            }
        }
    }
    if final_text.is_empty() {
        final_text = "(no response)".into();
    }

    // Persist both turns.
    {
        let db = state.app_db.lock();
        db.execute(
            "INSERT INTO chat_messages (session_id, role, content) VALUES (?1, 'user', ?2)",
            rusqlite::params![session_id, message],
        )
        .map_err(|e| CommandError::Sqlite(e.to_string()))?;
        db.execute(
            "INSERT INTO chat_messages (session_id, role, content) VALUES (?1, 'assistant', ?2)",
            rusqlite::params![session_id, final_text.clone()],
        )
        .map_err(|e| CommandError::Sqlite(e.to_string()))?;
        db.execute(
            "UPDATE chat_sessions SET updated_at = datetime('now') WHERE id = ?1",
            rusqlite::params![session_id],
        )
        .map_err(|e| CommandError::Sqlite(e.to_string()))?;
    }

    Ok(ChatResponse {
        session_id,
        message: final_text,
        role: "assistant".to_string(),
        charts,
    })
}

/// Direct invocation of the chart tool, exposed so the frontend can also
/// build charts outside of a chat context (future "chart from selection"
/// gesture, etc).
#[tauri::command]
pub fn make_chart(
    state: State<'_, AiAppState>,
    file_id: String,
    spec: ChartSpec,
) -> Result<ChartData, CommandError> {
    run_make_chart(&state, &file_id, spec)
}

fn run_make_chart(
    state: &AiAppState,
    file_id: &str,
    spec: ChartSpec,
) -> Result<ChartData, CommandError> {
    let stores = state.stores.lock();
    let store = stores
        .get(file_id)
        .ok_or_else(|| CommandError::UnknownFile(file_id.to_string()))?;
    chart::make_chart(store, spec).map_err(|e| match e {
        ChartError::Sql(s) => CommandError::Sqlite(s.to_string()),
        ChartError::UnknownColumn(c) => {
            CommandError::InvalidArg(format!("unknown column: {c}"))
        }
        ChartError::Invalid(m) => CommandError::InvalidArg(m),
    })
}

/// Compact JSON summary the LLM sees. The full payload (including data
/// rows) is shipped to the frontend separately — feeding all rows back
/// through the LLM would burn tokens and tempt hallucination.
fn chart_summary_for_llm(data: &ChartData) -> String {
    serde_json::json!({
        "rendered": true,
        "kind": data.spec.chart_type,
        "title": data.spec.title,
        "x_label": data.x_label,
        "y_label": data.y_label,
        "row_count": data.rows.len(),
        "series": data.series,
    })
    .to_string()
}

/// JSON-Schema for the chart tool. Kept in lockstep with `ChartSpec`.
fn chart_tool_definition() -> ToolDefinition {
    let schema = serde_json::json!({
        "type": "object",
        "properties": {
            "chartType": {
                "type": "string",
                "enum": [
                    "bar", "horizontal_bar", "stacked_bar", "grouped_bar",
                    "line", "area", "pie", "donut", "scatter", "histogram",
                    "treemap"
                ],
                "description": "Visual style. Use bar/pie for categorical; line/area for ordered/time-series; scatter for x↔y; histogram for the distribution of a single numeric column; stacked_bar/grouped_bar require a `groupBy` column for the second dimension."
            },
            "title": {"type": "string"},
            "xColumn": {"type": "string", "description": "Existing column name for the x-axis (or category for pie/donut/treemap, or source column for histogram)."},
            "yColumn": {"type": "string", "description": "Existing column name for the y-axis. Required unless aggregation = count."},
            "aggregation": {
                "type": "string",
                "enum": ["count", "sum", "avg", "min", "max"],
                "description": "Aggregate y over each x bucket. 'count' counts rows and ignores yColumn."
            },
            "groupBy": {"type": "string", "description": "Optional second column for stacked_bar / grouped_bar / multi-series line / multi-series area."},
            "limit": {"type": "integer", "description": "Cap the number of rows after sorting."},
            "order": {"type": "string", "enum": ["asc", "desc"], "description": "Sort by y value."},
            "binCount": {"type": "integer", "description": "For histogram only — number of equal-width buckets. Defaults to 12."}
        },
        "required": ["chartType", "title", "xColumn"]
    });
    ToolDefinition {
        name: "make_chart".to_string(),
        description:
            "Render a chart from the CSV currently open in this application. \
             You MUST call this tool whenever the user asks for a chart, \
             plot, graph, visualisation, distribution, breakdown, or 'show \
             me'. Do NOT write Python, matplotlib, plotly, vega, or any \
             other charting code in your reply — the app cannot execute it. \
             Only this tool produces a chart visible to the user. \
             You decide the chart_type and which columns to use; the system \
             runs the SQL and draws the chart, so do not invent any values. \
             After the tool returns, write a brief one-sentence interpretation."
                .to_string(),
        parameters: schema,
    }
}

// ---------------------------------------------------------------------------
// Feature 8 — Report builder
// ---------------------------------------------------------------------------

/// Generate and persist a structured Markdown report.
#[tauri::command]
pub async fn generate_report(
    state: State<'_, AiAppState>,
    file_id: String,
    request: String,
) -> Result<Report, CommandError> {
    let schema = get_schema(&state, &file_id)?;
    let llm = get_llm(&state)?;

    let (system, user_msg) = prompts::report_builder_prompt(&schema, &request);
    let resp: ReportLlmResponse = llm
        .complete_json(&system, &user_msg, 2048)
        .await
        .map_err(llm_error_to_command_error)?;

    let report_id = Uuid::new_v4().to_string();
    {
        let db = state.app_db.lock();
        db.execute(
            "INSERT INTO reports (id, file_path, report_type, title, content) \
             VALUES (?1, ?2, 'custom', ?3, ?4)",
            rusqlite::params![report_id, file_id, resp.title, resp.markdown],
        )
        .map_err(|e| CommandError::Sqlite(e.to_string()))?;
    }

    Ok(Report { report_id, title: resp.title, markdown: resp.markdown })
}

// ---------------------------------------------------------------------------
// Feature 9 — Join assistant
// ---------------------------------------------------------------------------

/// Ask the LLM to suggest join keys between two open files.
#[tauri::command]
pub async fn suggest_join(
    state: State<'_, AiAppState>,
    left_id: String,
    right_id: String,
) -> Result<JoinSuggestion, CommandError> {
    let left_schema = get_schema(&state, &left_id)?;
    let right_schema = get_schema(&state, &right_id)?;
    let llm = get_llm(&state)?;

    let (system, user_msg) = prompts::join_suggestion_prompt(&left_schema, &right_schema);
    let resp: JoinLlmResponse = llm
        .complete_json(&system, &user_msg, 256)
        .await
        .map_err(llm_error_to_command_error)?;

    Ok(JoinSuggestion {
        left_key: resp.left_key,
        right_key: resp.right_key,
        join_type: resp.join_type,
        rationale: resp.rationale,
    })
}

/// Execute a join between two open `SqliteStore` instances.
///
/// Returns a `FileInfo` for the result (registered as a new open file).
#[tauri::command]
pub fn execute_join(
    state: State<'_, AiAppState>,
    left_id: String,
    right_id: String,
    left_key: String,
    right_key: String,
    join_type: String,
) -> Result<crate::commands_csv::FileInfo, CommandError> {
    use csview_engine::join::{JoinSpec, JoinType};

    let join_type_enum = match join_type.to_uppercase().as_str() {
        "LEFT" => JoinType::Left,
        "RIGHT" => JoinType::Right,
        "FULL" => JoinType::Full,
        _ => JoinType::Inner,
    };

    // Read both sides while holding the lock.
    let (left_cols, left_headers, left_rows, right_cols, right_headers, right_rows) = {
        let stores = state.stores.lock();
        let left = stores
            .get(&left_id)
            .ok_or_else(|| CommandError::UnknownFile(left_id.clone()))?;
        let right = stores
            .get(&right_id)
            .ok_or_else(|| CommandError::UnknownFile(right_id.clone()))?;

        let left_cols: Vec<ColumnMeta> = left.columns().to_vec();
        let right_cols: Vec<ColumnMeta> = right.columns().to_vec();
        let left_headers: Vec<String> = left_cols.iter().map(|c| c.name.clone()).collect();
        let right_headers: Vec<String> = right_cols.iter().map(|c| c.name.clone()).collect();

        let lq = left.query("SELECT * FROM data").map_err(CommandError::from)?;
        let rq = right.query("SELECT * FROM data").map_err(CommandError::from)?;

        let to_rows = |res: csview_engine::sqlite_store::QueryResult| -> Vec<Vec<String>> {
            res.rows
                .into_iter()
                .map(|row| {
                    row.into_iter()
                        .map(|v| match v {
                            serde_json::Value::String(s) => s,
                            serde_json::Value::Null => String::new(),
                            other => other.to_string(),
                        })
                        .collect()
                })
                .collect()
        };

        (left_cols, left_headers, to_rows(lq), right_cols, right_headers, to_rows(rq))
    };

    // Find key column indices.
    let left_key_idx = left_cols
        .iter()
        .find(|c| c.name == left_key)
        .map(|c| c.index)
        .ok_or_else(|| CommandError::InvalidArg(format!("left key column '{left_key}' not found")))?;
    let right_key_idx = right_cols
        .iter()
        .find(|c| c.name == right_key)
        .map(|c| c.index)
        .ok_or_else(|| CommandError::InvalidArg(format!("right key column '{right_key}' not found")))?;

    let spec = JoinSpec {
        left_key: left_key_idx,
        right_key: right_key_idx,
        join_type: join_type_enum,
        fuzzy: false,
    };

    let join_result =
        csview_engine::join::join_datasets(&left_headers, &left_rows, &right_headers, &right_rows, &spec)
            .map_err(|e| CommandError::Sqlite(e.to_string()))?;

    let merged_headers = join_result.headers.clone();

    // Write to a temp CSV and re-import as a new store.
    let tmp = write_rows_to_tempfile(&merged_headers, &join_result.rows)?;
    let tmp_path = tmp.path().to_string_lossy().to_string();

    let sample: Vec<Vec<String>> = join_result.rows.iter().take(200).cloned().collect();
    let inferred_cols = crate::commands_csv::infer_columns_pub(&merged_headers, &sample);

    let new_store = csview_engine::sqlite_store::SqliteStore::from_csv(
        &tmp_path,
        b',',
        true,
        &merged_headers,
        &inferred_cols,
    )
    .map_err(CommandError::from)?;

    let schema = new_store.schema_context(5).map_err(CommandError::from)?;
    let result_id = Uuid::new_v4().to_string();
    let info = crate::commands_csv::FileInfo {
        file_id: result_id.clone(),
        path: tmp_path,
        row_count: new_store.row_count(),
        columns: schema.columns,
        table_name: new_store.table_name().to_string(),
    };

    state.stores.lock().insert(result_id, new_store);
    // Leak the temp file so the path stays valid for the store's lifetime.
    std::mem::forget(tmp);

    Ok(info)
}

/// Write rows to a temporary CSV file and return the handle.
fn write_rows_to_tempfile(
    headers: &[String],
    rows: &[Vec<String>],
) -> Result<tempfile::NamedTempFile, CommandError> {
    let tmp = tempfile::NamedTempFile::new().map_err(|e| CommandError::Io(e.to_string()))?;
    let mut wtr =
        csv::Writer::from_path(tmp.path()).map_err(|e| CommandError::Csv(e.to_string()))?;
    wtr.write_record(headers).map_err(|e| CommandError::Csv(e.to_string()))?;
    for row in rows {
        wtr.write_record(row).map_err(|e| CommandError::Csv(e.to_string()))?;
    }
    wtr.flush().map_err(|e| CommandError::Io(e.to_string()))?;
    Ok(tmp)
}

// ---------------------------------------------------------------------------
// Feature 10 — Compliance scan
// ---------------------------------------------------------------------------

/// Scan for PII columns using the quality module and ask the LLM to narrate.
#[tauri::command]
pub async fn compliance_scan(
    state: State<'_, AiAppState>,
    file_id: String,
) -> Result<ComplianceReport, CommandError> {
    let schema = get_schema(&state, &file_id)?;
    let llm = get_llm(&state)?;
    let (col_metas, rows) = read_all_rows(&state, &file_id)?;

    let mut pii_by_col: HashMap<String, (String, Vec<String>)> = HashMap::new();
    let mut all_pii_issues: Vec<QualityIssueSer> = Vec::new();

    for meta in &col_metas {
        let col_vals: Vec<&str> = rows
            .iter()
            .map(|r| r.get(meta.index).map(String::as_str).unwrap_or(""))
            .collect();
        for issue in quality::audit_column(&col_vals, meta, meta.index) {
            if let IssueType::PossiblePii(ref pii) = issue.issue_type {
                let pii_str = format!("{pii:?}");
                let entry = pii_by_col
                    .entry(meta.name.clone())
                    .or_insert_with(|| (pii_str, Vec::new()));
                if entry.1.len() < 5 {
                    entry.1.push(issue.value.clone());
                }
                all_pii_issues.push(QualityIssueSer::from(&issue));
            }
        }
    }

    let pii_columns: Vec<PiiColumn> = pii_by_col
        .into_iter()
        .map(|(col_name, (pii_kind, sample_values))| PiiColumn {
            column_name: col_name,
            pii_kind,
            sample_values,
        })
        .collect();

    let pii_json = serde_json::to_string_pretty(&all_pii_issues).unwrap_or_default();
    let (system, user_msg) = prompts::compliance_prompt(&schema, &pii_json);
    let markdown = llm
        .complete(&system, &user_msg, 768)
        .await
        .map_err(llm_error_to_command_error)?;

    Ok(ComplianceReport { markdown, pii_columns })
}

// ---------------------------------------------------------------------------
// Feature 11 — Forecast
// ---------------------------------------------------------------------------

/// Fit a linear regression on `(x_col, y_col)` and ask the LLM to interpret.
#[tauri::command]
pub async fn forecast(
    state: State<'_, AiAppState>,
    file_id: String,
    x_col: String,
    y_col: String,
) -> Result<ForecastReport, CommandError> {
    let schema = get_schema(&state, &file_id)?;
    let llm = get_llm(&state)?;
    let (col_metas, rows) = read_all_rows(&state, &file_id)?;

    let x_idx = col_metas
        .iter()
        .find(|c| c.name == x_col)
        .map(|c| c.index)
        .ok_or_else(|| CommandError::InvalidArg(format!("column '{x_col}' not found")))?;
    let y_idx = col_metas
        .iter()
        .find(|c| c.name == y_col)
        .map(|c| c.index)
        .ok_or_else(|| CommandError::InvalidArg(format!("column '{y_col}' not found")))?;

    let mut xs: Vec<f64> = Vec::new();
    let mut ys: Vec<f64> = Vec::new();
    for row in &rows {
        let xv = row.get(x_idx).and_then(|s| s.trim().parse::<f64>().ok());
        let yv = row.get(y_idx).and_then(|s| s.trim().parse::<f64>().ok());
        if let (Some(x), Some(y)) = (xv, yv) {
            xs.push(x);
            ys.push(y);
        }
    }

    let regression = stats_extended::linear_regression(&xs, &ys);
    let reg_json = serde_json::to_string_pretty(&regression).unwrap_or_default();

    let (system, user_msg) = prompts::forecast_prompt(&schema, &x_col, &y_col, &reg_json);
    let markdown = llm
        .complete(&system, &user_msg, 512)
        .await
        .map_err(llm_error_to_command_error)?;

    Ok(ForecastReport {
        markdown,
        slope: regression.slope,
        intercept: regression.intercept,
        r_squared: regression.r_squared,
        n: regression.n,
        x_col,
        y_col,
    })
}
